### ISSUE TITLE
Attack and armor types for more strategic elements

### ISSUE THREAD

**Issue by karlek** [Lapsang-boys/Rex-Temporis#77]
Is the added complexity not worth the tactical elements it provides? For instance, armor types could be:

- _Unarmored_: 120% damage from all towers (Stag, Dire Wolf, ...)
- _Normal_: 100% damage from all towers (Satyr, Furbolg)
- _Heavy_: 60% damage from piercing attack, 100% from magic, 120% from siege (Goblin War Machine)
- _Magical_: 100% damage from magic attack, 60% from piercing and siege.

I'm positive for the idea, but I know we've previously decided against it and I don't remember the counter-arguments. Complexity is usually something we value, where playing the map on easy mode is probably passable with a good maze and a small knowledge of the armor system. But, on hell mode the attack types are as important as tower placement.

What are your thoughts on this @godbit and @mewmew?

**Comment by mewmew** [comment]
> where playing the map on easy mode is probably passable with a good maze and a small knowledge of the armor system. But, on hell mode the attack types are as important as tower placement.

I quite like this approach. It's basically `/flying` on steroids. If this approach is taken, it is important that the turns should *never start on their own*, but always when the player issues `/next` or something along those lines. Then it's more to do with having build the *right* maze for a given level, selling it in between, etc. Than just micro-managing your builders. At least, this is something I would value, that the thorough thought of how to lay out the maze is important, not how quick you can sell your towers in between each round.

I very much like the armor vs. attack types as they make each enemy feel more unique. Also think there should be an undead that can only be killed by heal, e.g. Final Fantasy :)

**Comment by mewmew** [comment]
```diff
-Complexity is usually something we value
+Simplicity is usually something we value
```

**Comment by godbit** [comment]
I like the idea of having armor types that matter more on higher difficulties. 

1. I think it is very important that the map is not overwhelmingly complex for a new player (it should be intuitive enough for anyone who has played TDs before and not require to much reading about each tower) in order to finish the levels. Which is why i think armor types should be irrelevant on normal.

2. I think having armor types on higher difficulties adds depth to the map and will give the player more incentive to actively adapt its maze and towers for the current level.

- This could be solves through the level difficulty generation system. For easy-grade mobs the system defaults to "standard armor" (equal for all attack types). For the other difficulties it uses the armor type specified in that mobs unit definition. 

---------------------

@mew, we will never have auto spawning levels :unicorn:

**Comment by karlek** [comment]
1. I agree, which you also pointed out could be solved with our level generation system.
2. Sweet, we are going to have a hell of a time balancing this map later haha.

@mewmew Yeah, the `/flying` analogy is very accurate. Will be interesting to see how this will turn out.

**Comment by karlek** [comment]
1. I don't think they should be irrelevant, just that it should be possible to complete it without building with armor/attack types in mind. I think generating mobs without the armor class for lower difficulties removes an aspect that can be learned maybe in zone 3 when you have built your team 3 times. 
 
2. I agree! So much balancing will need to be made :camel: 

@mewmew Yeah, the `/flying` analogy is very accurate. Will be interesting to see how this will turn out, if it will change the economy of towers.

**Comment by godbit** [comment]
Ah i see, that could work as well. Cant wait to write the spreadsheet formula with armor types included :crossed_fingers:

**Comment by mewmew** [comment]
:unicorn:
