### ISSUE TITLE
Tests & Fixes & Misc thoughts about the missile branch

### ISSUE THREAD

**Issue by karlek** [Lapsang-boys/Rex-Temporis#87]
Tests

- Sea giant hit box vs rabbit

**Comment by karlek** [comment]
Implement `onReach` and `moveOverTime` for sword storm

**Comment by godbit** [comment]
z-movement is still iffy, we need to think about how we will handle this aswell.

If we would have move before launch towards target this could mean that "origin2" has a different height which would require a different approach when it comes to calculating the next height.
- My spontaneous thought is to use the current height instead of origin height to determine the next height but i have to think more about this. 
- Of course thers is alway 3d Runge–Kutta 4 :smirk:
